require "common.rb"

article "Leave Iran Alone!",
  :depth => 1 do
  p do
    text "By Dr. Ron Paul.  September 29, 2009."
    text "Retrieved from"
    honest_anchor "http://www.ronpaul.com/2009-09-29/ron-paul" +
      "-leave-iran-alone/"
    text "on 2009-10-04."
  end
  flush
  print <<-'!'

<p><strong>Jake in Houston:</strong> There seems to be a lot of hype and attention this weekend concerning the Iranian nuclear program. Why is that?</p>
<p><strong>Ron Paul: </strong>I don&#8217;t think it&#8217;s by accident. You know, all of a sudden it burst that up in Pittsburgh and all these charges were made. I think the number one reason why this all broke, because there&#8217;s really nothing new about what&#8217;s going on over in Iran. I think the reason is that the very, very powerful and the most militant neocons are very worried about Obama and other countries meeting with Iran and actually having negotiations with the government of Iran and they want to see it stopped. </p>
<p>I don&#8217;t think we have an anti-neocon administration, but I do think some of the people outside the administration, are very, very intent on stopping the negotiation and pursuing a very hard-line policy toward the Iranians. </p>
<p>The big charge was that all of a sudden there was this secret nuclear plant being built in Qom and that it had not been reported. Quite frankly, the way it got reported in the news was the Iranians reported it to IAEA, the United Nations investigation team and that&#8217;s how it became public and all of a sudden, they were jumped on for having done something secret. </p>

<p>Also, the truth is the United States knew about this since 2006. Obama was briefed on this in November right after he was elected. In 2007, there was an NIE, an intelligence estimate made in 2007, a year after we found out that they were doing something in Qom and it wasn&#8217;t even reported and the CIA report at that time said there was no evidence that the Iranians had been working on a nuclear weapon since 2003, so this is very much old news. </p>
<p>Now, the reason the argument is going on is, what does the law say? The Iranians, unlike three other countries in the Middle East, they don&#8217;t even pay any attention to and don&#8217;t even belong to the Non-Proliferation Treaty, but the Iranians&#8217; obligation under the law is that six months before they go into production, to do any enrichment for peaceful purposes, they have to notify the United Nations inspectors and they did exactly that, and yet they&#8217;re yelling and screaming now that they broke the law, that they&#8217;re on the verge of building a bomb. </p>
<p>You know what this sounds like? It sounds like warmongering. It sounds like the same old stuff that we heard prior to the Iraqi war. Remember the yellow cake with forged papers trying to say that Saddam Hussein was buying yellow cake and he was on the verge of a nuclear weapon or had nuclear weapons? It&#8217;s the same old thing going on and all the lies told that we were going to march in and find these nuclear weapons. </p>
<p>So it&#8217;s hysteria. It&#8217;s warmongering and unfortunately, the major media has not reported anything in balance whatsoever. They keep saying that the Iranians are on the verge. Of course, they&#8217;re talking tough. That&#8217;s the way they operate over there. It&#8217;s a tough neighborhood. That&#8217;s how they rise to power, so they are&#8230; you know, in many ways, rude and loudmouth, but that&#8217;s how tough guys exist over there and yet our response to them has been pretty irrational as well because I think the determination to add sanctions. </p>

<p>Right now, they continue this clamor for sanctions on the Iranians. &#8220;Don&#8217;t allow one drop of gasoline to be imported into the Iranians. Punish the people of Iran and that will bring them to their knees and they&#8217;ll throw out their ayatollahs and they&#8217;ll be friends with the West.&#8221; Quite frankly, it does exactly the opposite. It unifies the people of Iran. It does not help the dissidents in Iran and it actually&#8230; once we do this, pursue a policy like this, the real beneficiary are the Chinese because the Chinese happen to have a lot of dollars. They have a trillion dollars of our money, but they are not using bombs and weapons to influence and try to gain, you know, advantages in Iran. What they&#8217;re doing is they&#8217;re going in there and investing their money, so we, I believe, are on a completely wrong track. I think this is hysterical reaction that we ought to sit back and relax and look at the truth. </p>
<p>One of the reasons why this argument came up was that a few years ago, I think it was in 2003, the Iranians did sign a supplemental protocol with the West and they were in negotiations, and the protocol said that they would even report when they start building a nuclear facility, not just when they were getting ready to go into production, six months before production, but just when they started to build it. Now, they are building it and they&#8217;re said to be in violation of this. But the whole thing is, is that supplemental protocol, which was not a part of the original Non-Proliferation Treaty, they signed this willingly and it was never ratified by their parliament. You know, it would be like us having a president sign a treaty and never ratified by the Senate, it wouldn&#8217;t be the law of the land. And then the Iranian government announced precisely that they&#8217;re no longer following it because the negotiations were suspended by the West. They were negotiating with the Iranians and trying to come to an agreement and finally, they just said, &#8220;No, we&#8217;re not going to do it. If you&#8217;re not going to negotiate with us, we&#8217;re not going to follow this voluntary protocol.&#8221; </p>

<p>But the United Nations, the IAEA has never found the Iranians at fault. They have never been sanctioned. They have never broken the law. They have lived up to their commitment. </p>
<p>Now, the real problem politically is defending the kind of people who run Iran, but the whole truth is if you&#8217;re going to try to operate within the international law, we shouldn&#8217;t be so arrogant as to say that they&#8217;re doing such and such and they haven&#8217;t done it or they haven&#8217;t broken the law. So it&#8217;s time that we pay attention to our promises and our commitments rather than intimidating and threatening, putting on sanctions, which are an act of war and then setting the stage for ultimately bombing these facilities.</p>
<p>So to me, it sounds a whole lot like déjà vu, exactly the kind of nonsense that led us into a no-win, nonsensical war in Iraq where we&#8217;re still bogged down. We&#8217;re bogged down in Afghanistan and Pakistan and here they are trying to stir up another fight with another country. It is of no benefit to the American people. It is of no benefit to our national security interest and the sooner we get to the bottom of this and know the facts, the better off we would be as Americans.</p>


!
end # article
